apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: openapi-petstore-hpa
  namespace: openapi-petstore
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: openapi-petstore-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
